### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-colombian-biodiversity#6]
Do you need help figuring out how to customise the home page?

There is a set of predefined blocks that you can use, but I might be able to add more if you have anything specific in mind.

You can do so by adding a composition property to the frontmatter. E.g.

```yml
composition: # a list of blocks
  - type: heroImage # the block type
  - data: home.cardExample # the _data to use
    type: features # the block type
  - data: home.bannerExample2
    type: floatingText
  - data: home.splitExample
    type: split
```

So the [home page of the theme](https://hp-base-theme.gbif-staging.org/)
looks like https://github.com/gbif/jekyll-hp-base-theme/blob/master/pages/home.md

**Comment by MortenHofft** [comment]
The current choice of image might be temporary but the use of text on those hero images is tricky. The image will aim for full height and then crop if required. The image will [cover the area](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit). So the text might be fully are partially removed. If you have something specific in mind but are not sure how to do it, then let me know.

E.g. a tablet view removes your icon and parts of the text

<img width="836" alt="Screenshot 2021-03-04 at 09 04 13" src="https://user-images.githubusercontent.com/6759267/109931115-b6f8e380-7cc8-11eb-92e1-e03acd33d681.png">

**Comment by verovanporras** [comment]
Hi Morten!
Thanks for your help, I will keep that in mind for our visualizations, for now, I was doing some image tests, but yes, I want to create more content on the home page, I will do some tests today.

**Comment by camiplata** [comment]
@verovanporras  abro de nuevo el issue, la idea es cerrarlo cuando se solucione, en este caso cuanto tengas el layout del home listo, mientras se deja abierto para seguimiento y continuar la discusión o pedir ayuda de ser necesario.

**Comment by MortenHofft** [comment]
I've created an example of how the stats block can be used in a [new branch
](https://github.com/gbif/hp-colombian-biodiversity/commit/431c0c672a387555c5e9c5277aac2b0424e0a170)

Below is a screenshot. Notice there there is also custom css in this, since I wanted to demonstrate how you could port visual elements from your existing website. 

I hope that it is useful

<img width="849" alt="Screenshot 2021-03-09 at 18 31 16" src="https://user-images.githubusercontent.com/6759267/110512924-f6c72d00-8105-11eb-9ee4-2267672e0814.png">

**Comment by verovanporras** [comment]
Hi @MortenHofft, I have not been able to call up the _posts on the landing page that was on a preset start to see the most updated _posts. Could you help me with that?

**Comment by verovanporras** [comment]
@MortenHofft we did it! but now if you notice it drags the slide information.

**Comment by camiplata** [comment]
This is the behavior @verovanporras is describing:

<img width="1495" alt="Captura de Pantalla 2021-03-11 a la(s) 6 19 49 p  m" src="https://user-images.githubusercontent.com/5700527/110868561-d11d5d80-8296-11eb-8aa1-f97cc0b07722.png">

We added `- type: latestPosts` to the composition: section of the front matter of home.md

**Comment by MortenHofft** [comment]
It is assuming a data element
All the blocks take a data element and if none is provided it use the page data instead.

so if you added 

```yml
- type: latestPosts
  data: nonsense_is_not_a_folder # this would work despite not existing
```

Or the usual way
```yml
- type: latestPosts
  data: filename.propertyName
```

Or even inline
```yml
  - type: latestPosts
    inlineData: 
      title: Latest posts
      description: Some description could go here
      cta:
        - text: See all news
          href: /news
          isPrimary: true
```
